tasks:
  - before: |
      chmod 0755 database-setup.sh
      bash database-setup.sh
      pip install --upgrade pip
      python -m pip install Django==3.1.6 pytz==2019.2
      pip install -r requirements.txt
      python manage.py migrate
    command: |
      python manage.py runserver 0.0.0.0:8080
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - batisteo.vscode-django
